apiVersion: v1
kind: Service
metadata:
  name: my-svc-nodeport
  namespace: default
spec:
  ports:
  — name: web
    port: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: nginx
  type: NodePort

